version: '3.8'

services:
  kafka-kraft:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka-kraft
    hostname: kafka-kraft
    networks:
      - kafka-network
    ports:
      - "9101:9101"    # JMX
      - "9092:9092"    # External
      - "29092:29092"  # Internal Docker network
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-kraft:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka-kraft:29093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-kraft:29092,PLAINTEXT_EXTERNAL://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-kraft:29093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-kraft:29092"
      KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICATION: 1
      CLUSTER_ID: MTO0G7CmS4iKcyzLjCOT1w

  kafka-rest:
    image: confluentinc/cp-kafka-rest:7.9.0
    container_name: kafka-rest
    hostname: kafka-rest
    networks:
      - kafka-network
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-kraft:29092,PLAINTEXT_EXTERNAL://localhost:9092"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
    depends_on:
      - kafka-kraft

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.9.0
    container_name: control-center
    hostname: control-center
    networks:
      - kafka-network
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-kraft:29092"
      CONTROL_CENTER_REST_LISTENERS: "http://0.0.0.0:9021"
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: "http://kafka-rest:8082"
      CONTROL_CENTER_SCHEMA_REGISTRY_URLS: "http://schema-registry:8081"
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 4
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_ENABLE: "false"
      PORT: 9021
    depends_on:
      - kafka-kraft
      - kafka-rest
      - schema-registry
      - ksqldb-server

  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.0
    container_name: schema-registry
    hostname: schema-registry
    networks:
      - kafka-network
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-kraft:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    depends_on:
      - kafka-kraft

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.9.0
    container_name: ksqldb-server
    hostname: ksqldb-server
    networks:
      - kafka-network
    ports:
      - "8088:8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-kraft:29092"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_KSQL_SERVICE_ID: "ksql-server"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
    depends_on:
      - kafka-kraft

  ksqldb-cli:
    image: confluentinc/cp-ksqldb-cli:7.9.0
    container_name: ksqldb-cli
    networks:
      - kafka-network
    entrypoint: /bin/sh
    tty: true
    depends_on:
      - ksqldb-server

networks:
  kafka-network:

volumes:
  kafka-data:

